name = "tre-website"
main = ".open-next/worker.js"
compatibility_date = "2025-06-14"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true
head_sampling_rate = 1

# KV namespace for caching GitHub data
[[kv_namespaces]]
binding = "GITHUB_CACHE"
id = "github-cache"
preview_id = "github-cache-preview"

# Cron trigger to refresh GitHub data every 6 hours
[triggers]
crons = ["0 */6 * * *"]

[[routes]]
pattern = "tre.systems/*"
zone_name = "tre.systems"

[[routes]]
pattern = "www.tre.systems/*"
zone_name = "tre.systems"
