name = "tre-website"
main = ".open-next/worker.js"
compatibility_date = "2025-06-14"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true
head_sampling_rate = 1

[[routes]]
pattern = "tre.systems/*"
zone_name = "tre.systems"
