name = "tre-website"
main = ".open-next/middleware/handler.mjs"
compatibility_date = "2025-06-14"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"

[observability]
enabled = true
head_sampling_rate = 1

# KV namespace for caching GitHub data
[[kv_namespaces]]
binding = "GITHUB_CACHE"
id = "ef3c7113f48c46b8a04471c03ae0a428"
preview_id = "ef3c7113f48c46b8a04471c03ae0a428"

# Cron trigger to refresh GitHub data every 6 hours
[triggers]
crons = ["0 */6 * * *"]

[[routes]]
pattern = "tre.systems/*"
zone_name = "tre.systems"

[[routes]]
pattern = "www.tre.systems/*"
zone_name = "tre.systems"

# Secrets that need to be set via wrangler secret put
# Run these commands to set the secrets:
# wrangler secret put GITHUB_TOKEN
# wrangler secret put CLOUDFLARE_ACCOUNT_ID
# wrangler secret put CLOUDFLARE_IMAGES_API_TOKEN
# wrangler secret put CRON_SECRET
