name: Refresh GitHub Cache

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  schedule:
    # Run automatically every 6 hours (same as the original cron)
    - cron: '0 */6 * * *'

jobs:
  refresh-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh GitHub Cache
        run: |
          echo "🔄 Refreshing GitHub cache..."
          
          # Get the CRON_SECRET from GitHub secrets
          CRON_SECRET="${{ secrets.CRON_SECRET }}"
          
          if [ -z "$CRON_SECRET" ]; then
            echo "❌ CRON_SECRET not configured in GitHub secrets"
            echo "💡 Add CRON_SECRET to your repository secrets with the same value as in Cloudflare"
            exit 1
          fi
          
          # Call the cron endpoint to refresh the cache
          RESPONSE=$(curl -s -w "\n%{http_code}" \
            -H "Authorization: Bearer $CRON_SECRET" \
            "https://tre.systems/api/cron")
          
          # Extract response body and status code
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
          
          echo "📡 Response Status: $HTTP_STATUS"
          echo "📄 Response Body: $RESPONSE_BODY"
          
          if [ "$HTTP_STATUS" = "200" ]; then
            echo "✅ Cache refresh successful!"
          else
            echo "❌ Cache refresh failed with status $HTTP_STATUS"
            exit 1
          fi
          
      - name: Verify Cache Update
        run: |
          echo "🔍 Verifying cache was updated..."
          
          # Wait a moment for the cache to be populated
          sleep 5
          
          # Check if the site now shows projects
          RESPONSE=$(curl -s "https://tre.systems/")
          
          if echo "$RESPONSE" | grep -q "No projects found"; then
            echo "⚠️  Cache may still be empty - projects not showing"
          else
            echo "✅ Cache appears to be populated - projects are showing"
          fi
